---
title: "Seurat analysis of the prostate cancer data"
output: html_document
---

```{r init}
library(Seurat)
library(patchwork)

data1.2 <- as.sparse(read.csv("prostate-twelve/P1.2.tsv", sep='\t'))
data2.4 <- as.sparse(read.csv("prostate-twelve/P2.4.tsv", sep='\t'))
data3.3 <- as.sparse(read.csv("prostate-twelve/P3.3.tsv", sep='\t'))
colnames(data1.2) = paste0("1.2", colnames(data1.2))
colnames(data2.4) = paste0("2.4", colnames(data2.4))
colnames(data3.3) = paste0("3.3", colnames(data3.3))

seurat.data1.2 <- CreateSeuratObject(counts = data1.2, project = "Prostate1.2", min.cells = 2, min.features = 200)
seurat.data2.4 <- CreateSeuratObject(counts = data2.4, project = "Prostate2.4", min.cells = 2, min.features = 200)
seurat.data3.3 <- CreateSeuratObject(counts = data3.3, project = "Prostate3.3", min.cells = 2, min.features = 200)
d.list = c(seurat.data1.2, seurat.data2.4, seurat.data3.3)

# normalize each section independently & find variable genes
d.list <- lapply(X = d.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# features that are repeatedly variable
features <- SelectIntegrationFeatures(object.list = d.list)
```
```{r integrate}
anchors <- FindIntegrationAnchors(object.list = d.list, anchor.features = features)
combined <- IntegrateData(anchorset = anchors)
```

```{r pca}
# specify that we will perform downstream analysis on the corrected data (the original data is still in the 'RNA' assay)
DefaultAssay(combined) <- "integrated"

combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, npcs = 30, verbose = FALSE)
ElbowPlot(combined)
```



```{r clustering}
combined <- RunUMAP(combined, reduction = "pca", dims = 1:30)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:30)
combined <- FindClusters(combined, resolution = 0.5)
write.csv(Idents(combined), "seurat_clustering1_all_sections.csv", quote=F)

# Visualization
p1 <- DimPlot(combined, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```

```{r clustering}
combined <- FindClusters(combined, resolution = 0.9)
write.csv(Idents(combined), "seurat_clustering2_all_sections.csv", quote=F)

# Visualization
p1 <- DimPlot(combined, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```

```{r clustering}
combined <- RunUMAP(combined, reduction = "pca", dims = 1:10)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:10)
combined <- FindClusters(combined, resolution = 0.5)
write.csv(Idents(combined), "seurat_clustering3_all_sections.csv", quote=F)

# Visualization
p1 <- DimPlot(combined, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```

```{r clustering}
combined <- FindClusters(combined, resolution = 0.9)
write.csv(Idents(combined), "seurat_clustering4_all_sections.csv", quote=F)

# Visualization
p1 <- DimPlot(combined, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```


